### ISSUE TITLE
[Question] `setState` used in componentDidMount in fetch-github-stars example

### ISSUE THREAD

**Issue by royling** [developit/preact-www#153]
when I was trying to do the same thing in my own project, eslint suggests to avoid using `setState` in cDM lifecycle hook. And I found this discussion as well: https://github.com/yannickcr/eslint-plugin-react/issues/554, where it advised to disable eslint rules for some use cases though, I wonder if there's any other considerations in this fetch-github-star example. Is it better if moving the fetch call to `componentWillMount` hook instead?

**Comment by developit** [comment]
Hi @royling. The only real difference is that `componentWillMount()` is invoked during server-side rendering.  In this case, since the `setState()` call is within the callback of an async network request, it will just be silently ignored if invoked during server-side rendering.

The premise of avoiding `setState()` in `componentDidMount()` is that your first render will happen before `setState()` has updated state, making the first render pointless.  This is true in Preact as it is in React, but it only matters if you intend to invoke setState() synchronously without that lifecycle method.  Because the stars example is always async, it'll never resolve fast enough to inject that state before the first render anyway, so there's no difference.

**Comment by royling** [comment]
>it only matters if you intend to invoke setState() synchronously without that lifecycle method.

Thanks for answering it, that's very helpful.
