### ISSUE TITLE
Add Progressive Web Apps with Preact.js guide

### ISSUE THREAD

**Issue by addyosmani** [developit/preact-www#34]
Preact's lean nature makes it a pretty viable candidate for devs building [Progressive Web Apps](https://developers.google.com/web/progressive-web-apps/) to choose or switch out React for when shipping their production builds. The Preact site itself works great on [3G](https://twitter.com/slightlylate/status/770650491516772353?lang=en).

How would we feel about adding a one-page guide to shipping PWAs with Preact to the docs? 📚 

![image](https://cloud.githubusercontent.com/assets/110953/19696506/35d2db20-9a9c-11e6-96d3-2832c8115e85.png)

I believe most of the content in the [PWAs with React](https://addyosmani.com/blog/progressive-web-apps-with-react/) series should still apply to Preact. 👌
### Structure

I was thinking of summarizing:
Why Preact makes sense from an interactivity and load-performance POV for Progressive Web Apps.

or more broadly:

- Performance tooling: What webpack plugins / patterns (code-splitting, H/2 aggressive splitting, common chunk strategy, PRPL) that help you ship smaller bundles for each route
- Offline support / network resilience: list some of the options - Webpack plugin for [sw-precache](https://github.com/GoogleChrome/sw-precache), offline-plugin.

Remind folks throughout that it's time to interactivity that matters with PWAs and this tooling.

There's a lot of good existing material on these individual topics available out there, but bringing them all together in a high-level way and calling out where Preact fits in could be interesting.
### Preact as the optimisation choice for production React PWAs

Performance wise, we could show that even if you follow a lot of the best practices for trimming down your build sizes you are going to get to a point where your library bundles (e.g React) are what you can't trim down any smaller and that's a good place to drop Preact in. 

Here's an analysis of my bundles using React for a PWA:

![image](https://cloud.githubusercontent.com/assets/110953/19696595/a922ff60-9a9c-11e6-8697-7f160a127019.png)

and the after switching over to Preact:

![image](https://cloud.githubusercontent.com/assets/110953/19696655/f382dd96-9a9c-11e6-8b11-f4356502c765.png) 

Looking pretty nice. Get's interactive far quicker on real devices. ✨

Wdyt?

**Comment by developit** [comment]
@addyosmani - I'm 100% in favor of setting up a streamlined guide to building a PWA with Preact.

What's the best way to get started on this?  I can take a stab at coming up with an outline and some initial content if that works.

**Comment by developit** [comment]
/cc @TheLarkinn since he's got insight into the Webpack side of things.

Hopefilly this could stand as a better way to demystify the initial setup of preact + webpack + etc, currently dropping people into a boilerplate repo is a bit rough.

**Comment by addyosmani** [comment]
@developit Happy to riff with you on content! Want to take a look at an outline and we can iterate on it?  I think it would help folks for us to (at a high-level) call out the concepts and we would even shape up the guide around the same buckets [Lighthouse](https://github.com/googlechrome/lighthouse) covers in its reports.

@TheLarkinn was very insightful with my PWAs with React series and his input here would be very useful too.

**Comment by TheLarkInn** [comment]
Yes would be happy to assist.

**Comment by developit** [comment]
@addyosmani are you wanting to start with your three bullets from above?  I wonder how much preact-specific stuff makes sense for a guide, since the focus is on the structure of a PWA more than the "how" (if I'm following along correctly 😂)?

Also just some completely scattered thoughts from those screenshots - might be able to cut out timers-browserify?  We actually have an ~800-byte fetch polyfill at Synacor that needs to be open-sourced (whatwg-fetch is 2.4kb and breaks in IE8).

**Comment by addyosmani** [comment]
TBH I think the biggest thing Preact has to bring to the table here is improving how quickly folks can become interactive just based on the smaller payload. Does it make sense to focus on that and keep the other parts pretty high-level? 

Maybe...

1. We know Progressive web apps can be built with any framework (maybe link to existing literature)
2. One key part is instant loading - getting interactive quickly and instantly loading on subsequent visits. What does that mean? 1-2 liner on time-to-interactive.
3. How does Preact help here? 
  - Well, here's a Timeline/breakdown/visual/something of a highly optimised React app. As you can see, we start to hit limits with how much smaller we can get here. Here's how interactive we are. Here's our network payload. 
  - If we switch out React for Preact and preact-compat, we can get this same app working in NKB. It's interactive even faster. Preact for performant Progressive Web Apps ftw.

**Comment by developit** [comment]
Agreed regarding size being the main point.  Flow seems good to me.  Something like your bundle analysis screenshots (maybe colorized/simplified to make it super clear) might be good for 3.1, particularly since react-hn is one of the better examples of an optimized React app out there.

Thinking of links to point to for the first bit:

- [An obvious one](https://www.youtube.com/watch?v=srdKq0DckXQ) (video)
- [Your post on the topic](https://developers.google.com/web/updates/2015/12/getting-started-pwa)
- [Flipcart's writeup](https://medium.com/@AdityaPunjani/building-flipkart-lite-a-progressive-web-app-2c211e641883) (for a bit more of a React angle)

Then for TTI, maybe use the example of a static website but then pose the question "what if JavaScript is needed for interactivity?". Then talk about bundle size & lazy loading, interplay with server rendering.  Take-away being something like: it can be advantageous to server-render, but don't leave the user staring at an uninteractive snapshot of what they asked for.

For the third bit, I'm thinking since we've already touched on bundle size by then (and perhaps given some example sizes), making the comparison between total bundle size and the size of the framework used to render seems a natural progression.  The reader has context at that point to understand that 60kb gzipped really does matter when your entire JS bundle is 90kb gzipped.

**Comment by addyosmani** [comment]
> Then for TTI, maybe use the example of a static website but then pose the question "what if JavaScript is needed for interactivity?". Then talk about bundle size & lazy loading, interplay with server rendering. Take-away being something like: it can be advantageous to server-render, but don't leave the user staring at an uninteractive snapshot of what they asked for.

💯 I think covering this would be super useful. I would try to stress that even with code-splitting, you've got to make sure you're still shipping down as little as possible for a route, focusing on making it useful and interactive for the user quickly (seeing lots of folks code-split and still ship large chunks atm. oof). But I think Preact's part of this story, where it helps you keep the library parts of these thin bundles even smaller than React and maybe even gives you some more budget for code if you're already pretty small are good stories to tell.

> The reader has context at that point to understand that 60kb gzipped really does matter when your entire JS bundle is 90kb gzipped.

SGTM. I would be happy to get over numbers and before/after build comparisons if useful but equally as happy to help with reviews.

**Comment by developit** [comment]
@addyosmani - was just wondering this and I agree, number comparisons can sort of take away from the point of things. I wonder if there are contextually meaningful targets we could convey though, something like being able to render an interactive page (the actual request content) withing a single TCP packet. Those still allow for framing via numbers ("woah that's a lot less than my app's current 1.2mb of JS"), but keep focus on the factors that actually affect TTI in constrained environments. 

Thoughts?

**Comment by Download** [comment]
LOL this is a great idea! I actually switched to Preact from React to achieve these goals of shorter time to interactivity and it really is worth it! Too bad this didn't exist when I started  😋

**Comment by addyosmani** [comment]
@developit It was great meeting you at Chrome Dev Summit, even if just from across the stage :)

On structure, I wonder if something like this could work:

Preact is a great choice if you're looking for a drop-in way for your (React) Progressive Web App  to load and become interactive quicker.

- Less code, loaded better improves perf
  - In many places, mobile has taken over desktop. Mobile users have constrained networks (3G) & hardware but the average page on mobile takes 19s to load. That's way too long.
  - Shipping larger bundles of JS can leave users waiting a long time before they can interact with your single-page app. Large JS bundles don't just impact load - it also impacts parse and compile times. 
  - This is where Preact can help!
- Preact helps you load and get interactive quicker
  - If you're trying to load fast and get interactive fast, it helps keeping your bundles small. 
  - React is awesome but has a larger footprint than Preact and can take longer to get you interactive. 
  - Dropping Preact in your projects shaves N KB off (on average) and can take your dependency graph from looking like this (A) to this (B). It also enables you to get interactive in one RTT.
  - This loads faster while still allowing you to use React Router and the ecosystem of libraries you're used to using with React. 

Getting interactive quickly (in <5s) is achievable with less effort using Preact, making it a great fit for folks building Progressive Web Apps.

Thoughts?

**Comment by developit** [comment]
I really enjoyed your talk! Need to get out to more conferences, it was fun to run into people.

That structure looks really good, I like breaking things up at the top level in order to bundle size and TTI as separate things (thinking about the Lighthouse metrics in my head as I read).

I'd like to add some art to a bunch of the pages since right now things look a little bit like a readme (since the site used to be a readme).  I can think of some neat graphics to go along with your bullets!

I was envious of the swanky vector art in your slides 😍

**Comment by addyosmani** [comment]
> I really enjoyed your talk! Need to get out to more conferences, it was fun to run into people.

Will hopefully run into you again sometime. You definitely have a number of fans on the Chrome team :)

> That structure looks really good, I like breaking things up at the top level in order to bundle size and TTI as separate things (thinking about the Lighthouse metrics in my head as I read).

Really glad to hear that. Would a "Progressive Web Apps" addition to the Guide section be the best place to flesh out some of this content?

> I was envious of the swanky vector art in your slides 

Maybe we can sneak some into this doc :)

**Comment by developit** [comment]
Yes, on all accounts.  Adding the a markdown file in `content/guide/` will auto-deploy it once merged, so I guess we'll start there. Want to create it, or should I?

**Comment by addyosmani** [comment]
I would be happy to create it and maybe we can iterate on the content together?

**Comment by developit** [comment]
Absolutely. Adding you as a collab
