### ISSUE TITLE
Preact spanish translations are not neutral

### ISSUE THREAD

**Issue by Download** [developit/preact-www#90]
@erasmo-marin [said](https://github.com/developit/preact/issues/529):

> Preact translations to spanish are in argentinian spanish, and it should be neutral spanish.
> 
> Usá Preact -- should be --> Usa Preact
> 
> La liviandad es mucho más divertida cuando no tenés que sacrificar productividad -- should be --> La liviandad es mucho más divertida cuando no tienes que sacrificar productividad
> 
> Elegí la guía que funciona mejor para vos! -- should be --> Elige la guía que funciona mejor para ti!
> 
> etc etc... it's annoying. I'm free to help you to fix translations.
> 
> Thanks.

**Comment by Download** [comment]
The issue tracker for the website is here:
https://github.com/developit/preact-www

The spanish translations are here:
https://github.com/developit/preact-www/tree/master/content/lang/es

To help, you can fork the `preact-www` repo, clone it to your machine, **create and switch to a new branch** (important!) and then change whatever needs changing. Once done, commit and push. In Github you will then see a button to create a PR. Push it!  :)

May I suggest you copy the existing translations and rename the folder to `es-ar` (argentinian spanish), then make `es` be neutral spanish.

**Comment by developit** [comment]
I'm fine with using only neutral Spanish, or the `es` + `es-ar` solution @Download proposed. I don't know enough about Spanish to know which is preferable.  If the differences are minimal though, it'd be really nice to only have to maintain one translation (likely neutral Spanish).

**Comment by Download** [comment]
Good point about maintenance

**Comment by erasmo-marin** [comment]
Thanks, sorry for opening the issue in the wrong repository, I searched for it but couldn't find it.

The best solution for me is just to use the neutral spanish, it doesn't make sense to me to have a separate locale just for Argentina.

Just to give some context to this conversation, Argentinian spanish is just a different accent accepted as correct spanish (and they write it as they say it) but that it's only used in Argentina. Argentinian people doesn't have problem to understand neutral spanish, because it's just the same, and it's used in movies, tv shows, etc.

So if it's not a problem, I will just overwrite the translations without creating a specific translation for es-ar.

**Comment by developit** [comment]
I'm fine with that.  Managing translations is already a tough job since the documentation website is always being updated, so it's good to be able to share a language for a bunch of countries as long as it's understandable to all.  Happy to accept a PR!

**Comment by impronunciable** [comment]
+1 to make it neutral. I can help reviewing the PR if necessary

**Comment by Download** [comment]
@erasmo-marin Let us know if you need help with the PR process... it can be a bit daunting if you've never done it before but we are here to help.
